[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  schedule = "* * * * *"
  node_bundler = "esbuild"

[functions."*"]
  external_node_modules = ["axios", "@supabase/supabase-js"]