backend:
  name: git-gateway
  repo: nurdanab/steppe-coffee-new
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "promotions"
    label: "Промо-акции"
    files:
      - name: "promoData"
        label: "Данные промо-акций"
        file: "src/data/promotionsData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "promoSlot1"
            label: "Промо Слот 1"
            widget: "object"
            fields:
              - label: "ID Слота 1"
                name: "id"
                widget: "string"
                default: "promo_card_1"
              - label: "Изображение Слота 1"
                name: "imageUrl"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/promos"
                public_folder: "/images/promos"

          - name: "promoSlot2"
            label: "Промо Слот 2"
            widget: "object"
            fields:
              - label: "ID Слота 2"
                name: "id"
                widget: "string"
                default: "promo_card_2"
              - label: "Изображение Слота 2"
                name: "imageUrl"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/promos"
                public_folder: "/images/promos"

  - name: "bookCorner"
    label: "Книжный Уголок"
    files:
      - name: "bookCornerData"
        label: "Данные Книжного Уголка"
        file: "src/data/bookCornerData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "mainBook"
            label: "Основная Книга"
            widget: "object"
            fields:
              - label: "Изображение Основной Книги"
                name: "imageSrc"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/bookShelf"
                public_folder: "/images/bookShelf"

          - name: "bookShelf"
            label: "Книжная Полка"
            widget: "object"
            fields:
              - name: "books"
                label: "Книги"
                widget: "list"
                allow_add: true
                allow_delete: true
                collapsed: true
                fields:
                  - label: "ID Книги"
                    name: "id"
                    widget: "string"
                    required: true
                    hint: "Используется для внутренней идентификации книги. Не меняйте, если не уверены."
                  - label: "Название Книги"
                    name: "title"
                    widget: "string"
                    required: true
                  - label: "Автор"
                    name: "author"
                    widget: "string"
                  - label: "Обложка Книги"
                    name: "coverImage"
                    widget: "image"
                    allow_multiple: false
                    media_folder: "public/images/bookShelf"
                    public_folder: "/images/bookShelf"

  - name: "deskItems"
    label: "Элементы на доске"
    files:
      - name: "deskData"
        label: "Данные Элементов на доске"
        file: "src/data/deskData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "items"
            label: "Список Элементов"
            widget: "list"
            allow_add: true
            allow_delete: true
            collapsed: true
            fields:
              - name: "id"
                label: "ID"
                widget: "uuid"
              - name: "type"
                label: "Тип Элемента"
                widget: "select"
                options:
                  - { label: "Текстовый Стикер", value: "sticker" }
                  - { label: "Декорация с Булавкой", value: "decoration_with_pin" }
                  - { label: "Стикер Сайгак", value: "saigak_sticker" }
                required: true
            types:
              - name: "sticker"
                label: "Текстовый Стикер"
                widget: "object"
                fields:
                  - { name: "text", label: "Текст Стикера", widget: "string", required: true }
                  - name: "position"
                    label: "Позиция"
                    widget: "object"
                    fields:
                      - { name: "top", label: "Top (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "left", label: "Left (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "transform", label: "Transform (CSS)", widget: "string", required: false }
                      - { name: "zIndex", label: "Z-Index", widget: "number", value_type: "int" }
                  - { name: "stickerColor", label: "Цвет Стикера", widget: "string", required: false }

              - name: "decoration_with_pin"
                label: "Декорация с Булавкой"
                widget: "object"
                fields:
                  - { name: "imageSrc", label: "Изображение", widget: "image", allow_multiple: false, media_folder: "public/images/desk/detail", public_folder: "/images/desk/detail" }
                  - name: "position"
                    label: "Позиция"
                    widget: "object"
                    fields:
                      - { name: "top", label: "Top (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "left", label: "Left (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "transform", label: "Transform (CSS)", widget: "string", required: false }
                      - { name: "zIndex", label: "Z-Index", widget: "number", value_type: "int" }
                  - { name: "pinType", label: "Тип Булавки", widget: "string", required: false }
                  - name: "pinOffset"
                    label: "Смещение Булавки"
                    widget: "object"
                    fields:
                      - { name: "top", label: "Top (px)", widget: "number", value_type: "int" }
                      - { name: "left", label: "Left (px)", widget: "number", value_type: "int" }
                      - { name: "rotate", label: "Поворот (deg)", widget: "string", required: false }
                      - { name: "zIndex", label: "Z-Index", widget: "number", value_type: "int" }

              - name: "saigak_sticker"
                label: "Стикер Сайгак"
                widget: "object"
                fields:
                  - { name: "text", label: "Текст Сайгак Стикера", widget: "string", required: true }
                  - { name: "saigakImageSrc", label: "Изображение Сайгака", widget: "image", allow_multiple: false, media_folder: "public/images/desk/detail", public_folder: "/images/desk/detail" }
                  - { name: "backgroundShape", label: "Форма Фона", widget: "select", options: ["oval", "circle", "rectangle"], default: "oval" }
                  - { name: "backgroundColor", label: "Цвет Фона", widget: "string", required: false }
                  - { name: "textColor", label: "Цвет Текста", widget: "string", required: false }
                  - name: "position"
                    label: "Позиция"
                    widget: "object"
                    fields:
                      - { name: "top", label: "Top (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "left", label: "Left (%)", widget: "number", value_type: "float", min: 0, max: 100, step: 0.1 }
                      - { name: "transform", label: "Transform (CSS)", widget: "string", required: false }
                      - { name: "zIndex", label: "Z-Index", widget: "number", value_type: "int" }
                  - { name: "pinType", label: "Тип Булавки", widget: "string", required: false }
                  - name: "pinOffset"
                    label: "Смещение Булавки"
                    widget: "object"
                    fields:
                      - { name: "top", label: "Top (px)", widget: "number", value_type: "int" }
                      - { name: "left", label: "Left (px)", widget: "number", value_type: "int" }
                      - { name: "rotate", label: "Поворот (deg)", widget: "string", required: false }
                      - { name: "zIndex", label: "Z-Index", widget: "number", value_type: "int" }          