backend:
  name: github
  repo: nurdanab/steppe-coffee-new # Замените на ваш репозиторий
  branch: main # Ветка, в которую CMS будет коммитить изменения

media_folder: "public/images" # Где хранить загруженные изображения (относительно корня репозитория)
public_folder: "/images" # Как изображения будут доступны на вашем сайте (относительно корня сайта)

collections:
  # Здесь мы будем определять коллекции контента позже