backend:
  name: git-gateway
  repo: nurdanab/steppe-coffee-new
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "promotions"
    label: "Промо-акции"
    files:
      - name: "promoData"
        label: "Данные промо-акций"
        file: "src/data/promotionsData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "promoSlot1"
            label: "Промо Слот 1"
            widget: "object"
            fields:
              - label: "ID Слота 1"
                name: "id"
                widget: "string"
                default: "promo_card_1"
              - label: "Изображение Слота 1"
                name: "imageUrl"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/promos"
                public_folder: "/images/promos"

          - name: "promoSlot2"
            label: "Промо Слот 2"
            widget: "object"
            fields:
              - label: "ID Слота 2"
                name: "id"
                widget: "string"
                default: "promo_card_2"
              - label: "Изображение Слота 2"
                name: "imageUrl"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/promos"
                public_folder: "/images/promos"

  - name: "bookCorner"
    label: "Книжный Уголок"
    files:
      - name: "bookCornerData"
        label: "Данные Книжного Уголка"
        file: "src/data/bookCornerData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "mainBook"
            label: "Основная Книга"
            widget: "object"
            fields:
              - label: "Изображение Основной Книги"
                name: "imageSrc"
                widget: "image"
                allow_multiple: false
                media_folder: "public/images/bookShelf"
                public_folder: "/images/bookShelf"

          - name: "bookShelf"
            label: "Книжная Полка"
            widget: "object"
            fields:
              - name: "books"
                label: "Книги"
                widget: "list"
                allow_add: true
                allow_delete: true
                collapsed: true
                fields:
                  - label: "ID Книги"
                    name: "id"
                    widget: "string"
                    required: true
                    hint: "Используется для внутренней идентификации книги. Не меняйте, если не уверены."
                  - label: "Название Книги"
                    name: "title"
                    widget: "string"
                    required: true
                  - label: "Автор"
                    name: "author"
                    widget: "string"
                  - label: "Обложка Книги"
                    name: "coverImage"
                    widget: "image"
                    allow_multiple: false
                    media_folder: "public/images/bookShelf"
                    public_folder: "/images/bookShelf"

  - name: "deskItems"
    label: "Элементы на доске"
    files:
      - name: "deskData"
        label: "Данные Элементов на доске"
        file: "src/data/deskData.json"
        format: "json"
        editor: {}
        preview: false
        fields:
          - name: "items"
            label: "Текста на стикерах"
            widget: "list"
            allow_add: false
            allow_delete: false
            collapsed: false
            fields:
              - name: "id"
                label: "ID стикера"
                widget: "string"
                disabled: true
            types:
              - name: "sticker"
                label: "Новостной Стикер"
                widget: "object"
                fields:
                  - { name: "text", label: "Текст Стикера", widget: "string", required: true }         
              - name: "decoration_with_pin"
                label: "Декорация (не редактируется)"
                widget: "object"
                fields:
              - name: "saigak_sticker"
                label: "Стикер Сайгак"
                widget: "object"
                fields:
                  - { name: "text", label: "Текст Сайгак Стикера", widget: "string", required: true }